export const DemoPath = {
    Overview: 'getting-started/overview',
    Installation: 'getting-started/installation',
    Quickstart: 'getting-started/quickstart',
    CoreConcepts: 'getting-started/core-concepts',
    ConfigurationAndPublicApi: 'features/configuration-and-public-api',
    PanZoom: 'features/pan-zoom-configuration',
    Nodes: 'features/creating-nodes',
    Connectors: 'features/connectors',
    Connections: 'features/connections',
    Validation: 'features/validation',
    SimpleExample: 'examples/simple-example',
    ExamplesOverview: 'examples/overview',
    Editor: 'examples/editor',
    StressTest: 'examples/stress-test',
    CustomNodes: 'examples/nodes-example/custom-nodes-example',
} as const;
