export const DemoPath = {
    Quickstart: 'documentation/quickstart',
    Migrations: 'documentation/migrations',
    TermsAndDefinitions: 'documentation/terms-and-definitions',
    ConfigurationAndPublicApi: 'documentation/configuration-and-public-api',
    StateAndEvents: 'documentation/state-and-events',
    PanZoom: 'documentation/pan-zoom-configuration',
    Nodes: 'documentation/creating-nodes',
    Connectors: 'documentation/connectors',
    Layouts: 'documentation/layouts',
    Connections: 'documentation/connections',
    Labels: 'documentation/labels',
    Validation: 'documentation/validation',
    SimpleExample: 'examples/simple-example',
    Overview: 'examples/overview',
    Editor: 'examples/editor',
    DynamicLayout: 'examples/dynamic-layout',
    StressTest: 'examples/stress-test',
    CustomNodes: 'examples/nodes-example/custom-nodes-example',
} as const;
