name: Deploy / preview

on: pull_request

jobs:
  build_and_preview:
    name: Firebase
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
      - uses: taiga-family/ci/actions/setup/variables@e9c5cd341c28d9aeb357b757df41cddcbb674b2d # v1.222.0
      - uses: taiga-family/ci/actions/setup/node@e9c5cd341c28d9aeb357b757df41cddcbb674b2d # v1.222.0
      - run: npm run build

      - name: Debug output
        run: tree dist/demo/browser -P '*.html'
      - name: Deploy preview
        uses: FirebaseExtended/action-hosting-deploy@e2eda2e106cfa35cdbcf4ac9ddaf6c4756df2c8c # v0
        if: env.IS_OWNER_MODE == 'true'
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_NG_DRAW_FLOW }}
          projectId: ng-draw-flow
          expires: 1d

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
